#!/bin/sh
exec /media/ubuntu/RESERVE0/workspace/build.rel/./bin/llvm-goc "$@" -I /media/ubuntu/RESERVE0/workspace/build.rel/tools/gollvm/libgo -L /media/ubuntu/RESERVE0/workspace/build.rel/tools/gollvm/libgo 
